import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Navigation } from "./components/navigation";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Foooter from "./components/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className="h-full">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased flex flex-col min-h-screen`}
        >
          {/* <header className="bg-slate-900 text-white py-2 px-4 text-center shadow-sm"> */}
            <Navigation />
          {/* </header> */}
          <main className="flex-grow">{children}</main>
          <Foooter/>
        </body>
      </html>
    </ClerkProvider>
  );
}
